routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PostController@explore');

Route::get('/post/explore', 'PostController@explore')->name('post.explore');
Route::group(['middleware' => ['auth']], function () {
    Route::resource('post', 'PostController', ['except' => ['show']]);

    Route::resource('profile', 'ProfileController');

    Route::post('/follow/{follow}', 'FollowController@store')->name('follow.store');
    Route::delete('/follow/{follow}', 'FollowController@destroy')->name('follow.destroy');

    Route::post('/postlike/{postlike}', 'PostLikeController@store')->name('postlike.store');
    Route::delete('/postlike/{postlike}', 'PostLikeController@destroy')->name('postlike.destroy');

    Route::resource('komentar', 'KomentarController');

    Route::post('/komentarlike/{komentarlike}', 'KomentarLikeController@store')->name('komentarlike.store');
    Route::delete('/komentarlike/{komentarlike}', 'KomentarLikeController@destroy')->name('komentarlike.destroy');
});

Route::resource('post', 'PostController', ['only' => ['show']]);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //
    protected $fillable = ['gambar', 'konten', 'user_id'];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function postLike()
    {
        return $this->hasMany('App\PostLike');
    }

    public function komentar()
    {
        return $this->hasMany('App\Komentar');
    }


    public function likedBy(User $user)
    {
        return $this->postLike->contains('user_id', $user->id);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $user = Auth::user();
        $userIds = $user->following->pluck('id')->toArray();
        $userIds[] = $user->id;
        $posts = Post::whereIn('user_id', $userIds)->orderBy('created_at', 'DESC')->get();
        // $posts = Post::all()->sortByDesc("created_at");
        return view('post.index', compact('posts'));
    }

    public function explore()
    {
        //
        if (Auth::user()) {
            $user = Auth::user();
            $userIds = $user->following->pluck('id')->toArray();
            $userIds[] = $user->id;
            $posts = Post::whereNotIn('user_id', $userIds)->orderBy('created_at', 'DESC')->get();
            // $posts = Post::all()->sortByDesc("created_at");
            return view('post.index', compact('posts'));
        } else {
            $posts = Post::all()->sortByDesc("created_at");
            return view('post.index', compact('posts'));
        }
    }

    public function guest()
    {
        //
        $posts = Post::all();
        // $posts = Post::all()->sortByDesc("created_at");
        return view('post.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('post.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'gambar' => 'required|mimes:png,jpg,jpeg|max:5000',
            'konten' => 'required',
        ]);

        $gambar = $request->gambar;
        $new_gambar = time() . '-' . $gambar->getClientOriginalName();
        $post = Post::create([
            "gambar" => $new_gambar,
            "konten" => $request["konten"],
            "user_id" => Auth::user()->id,
        ]);

        $gambar->move('gambar/', $new_gambar);

        return redirect('/post')->with('success', 'Post berhasil ditambahkan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $post = Post::find($id);
        return view('post.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $post = Post::find($id);
        return view('post.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $request->validate([
            'gambar' => 'mimes:png,jpg,jpeg|max:5000',
            'konten' => 'required',
        ]);

        $post = Post::findorfail($id);

        if ($request->has('gambar')) {
            $path = "gambar/";
            File::delete($path . $post->gambar);
            $gambar = $request->gambar;
            $new_poster = time() . '-' . $gambar->getClientOriginalName();
            $gambar->move('gambar/', $new_poster);
            $post_data = [
                "gambar" => $new_poster,
                "konten" => $request["konten"],
            ];
        } else {
            $post_data = [
                "konten" => $request["konten"],
            ];
        }

        $post->update($post_data);

        return redirect('/post')->with('success', 'Post berhasil diupdate!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $post = Post::findorfail($id);
        $post->postLike()->delete();
        foreach ($post->komentar as $komentar) {
            $komentar->komentarLike()->delete();
            $komentar->delete();
        }
        $path = "gambar/";
        File::delete($path . $post->gambar);

        $post->delete();


        return redirect('/post')->with('success', 'Post berhasil dihapus!');
    }
}

resources/views/post/create.blade.php
@extends('adminlte.master')

@section('content')
<div class="card card-primary mt-3 mx-3">
    <div class="card-header">
        <h3 class="card-title">Add Post</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form action="{{ route('post.store')}}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="card-body">
            <div class="form-group">
                <label for="gambar">Gambar</label>
                <input type="file" class="form-control" id="gambar" name="gambar" value="{{ old('gambar','') }}"
                    placeholder="Masukkan gambar">
                @error('gambar')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label for="konten">Konten</label>
                <textarea name="konten" id="konten" class="form-control"
                    placeholder="konten">{{ old('konten','') }}</textarea>
                @error('konten')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Add</button>
        </div>
    </form>
</div>
@endsection

resources/views/post/edit.blade.php
@extends('adminlte.master')

@section('content')
<div class="card card-primary mt-3 mx-3">
    <div class="card-header">
        <h3 class="card-title">Edit Post</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form action="{{ route('post.update',['post'=>$post->id])}}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="card-body">
            <div class="form-group">
                <label for="gambar">Gambar</label>
                <input type="file" class="form-control" id="gambar" name="gambar"
                    value="{{ old('gambar',$post->gambar) }}" placeholder="Masukkan gambar">
                @error('gambar')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label for="konten">Konten</label>
                <textarea name="konten" id="konten" class="form-control"
                    placeholder="konten">{{ old('konten',$post->konten) }}</textarea>
                @error('konten')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Edit</button>
        </div>
    </form>
</div>
@endsection

resources/views/post/index.blade.php
@extends('adminlte.master')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                @if(Route::is('post.index'))
                <h1>Home</h1>
                @else
                <h1>Explore</h1>
                @endif
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- /.col -->
            <div class="col-md-12">
                <div class="card">
                    @auth
                    <div class="card-header p-2">
                        @if(Route::is('post.index'))
                        <a href="{{ route('post.create') }}" class="btn btn-primary my-2">Add Post</a>
                        @endif
                    </div><!-- /.card-header -->
                    @endauth
                    <div class="card-body">
                        @forelse ($posts as $post)
                        <!-- Post -->
                        <div class="post">
                            <div class="user-block">
                                <img class="img-circle img-bordered-sm" src="{{ asset('adminlte/dist/img/guest.png') }}"
                                    alt="user image">
                                <span class="username">
                                    <a
                                        href="{{ route('profile.show',['profile' => $post->user->profile->id]) }}">{{ $post->user->profile->username }}</a>

                                </span>
                                <span class="description">{{ $post->created_at->format('H:i d/m/Y') }}</span>
                            </div>
                            <!-- /.user-block -->

                            <div class="row mb-3">
                                <div class="col-sm-6">
                                    <img class="img-fluid" src="{{ asset('gambar/' . $post->gambar) }}" alt="Photo">
                                </div>
                                <div class="row ml-2">
                                    <p>
                                        {{ $post->konten }}
                                    </p>
                                </div>
                            </div>

                            <p>
                                <a href="#" class="link-black text-sm btn-link disabled"><i
                                        class="far fa-thumbs-up mr-1"></i>
                                    {{ $post->postLike->count() }} Like</a>
                                <a href="{{ route('post.show',['post' => $post->id]) }}"
                                    class="link-black text-sm btn-link disabled">
                                    <i class="far fa-comments mr-1"></i> Comments
                                    ({{ $post->komentar->count() }})
                                </a>
                                @auth
                                <div class="d-flex">
                                    @if (!$post->likedBy(auth()->user()))
                                    <form action="{{ route('postlike.store',['postlike'=>$post->id]) }}" method="POST">
                                        @csrf
                                        <button type="submit" class="btn btn-primary btn-sm  mr-2"><i
                                                class="far fa-heart ml-0 mr-1"></i> Like</button>
                                    </form>
                                    @else
                                    <form action="{{ route('postlike.destroy',['postlike'=>$post->id]) }}"
                                        method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-secondary btn-sm  mr-2"><i
                                                class="fas fa-heart-broken ml-0 mr-1"></i> Unlike</button>
                                    </form>
                                    @endif
                                    <a href="{{ route('post.show',['post' => $post->id]) }}"
                                        class="btn btn-primary btn-sm  mr-2"><i class="far fa-comments ml-1 mr-1"></i>
                                        Comment</a>
                                    @if ($post->user_id === Auth::user()->id)
                                    <a href="{{ route('post.edit',['post' => $post->id]) }}"
                                        class="btn btn-info btn-sm  mr-2"><i class="far fa-edit ml-1 mr-1"></i>
                                        Edit</a>
                                    <form action="{{ route('post.destroy', ["post" => $post->id]) }}" method="POST">
                                        @csrf
                                        @method("DELETE")
                                        <button type="submit" class="btn btn-danger btn-sm  ml-0"><i
                                                class="far fa-trash-alt ml-1 mr-1"></i> Delete</button>
                                    </form>
                                    @endif
                                </div>
                                @endauth
                                @guest
                                <div class="d-flex">
                                    <a href="{{ route('post.show',['post' => $post->id]) }}"
                                        class="btn btn-primary btn-sm  mr-2"><i class="far fa-comments ml-1 mr-1"></i>
                                        Comment</a>
                                </div>
                                @endguest
                            </p>
                        </div>
                        <!-- /.post -->
                        @empty
                        @if(Route::is('post.index'))
                        <p>No Post Yet</p>
                        @else
                        <p>No Post to Explore Yet</p>
                        @endif

                        @endforelse
                        <div class="tab-content">
                        </div>
                        <!-- /.tab-content -->
                    </div><!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection

resources/views/post/show.blade.php
@extends('adminlte.master')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                <h1>Post</h1>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- /.col -->
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <!-- Post -->
                        <div class="post">
                            <div class="user-block">
                                <img class="img-circle img-bordered-sm" src="{{ asset('adminlte/dist/img/guest.png') }}"
                                    alt="user image">
                                <span class="username">
                                    <a href="#">{{ $post->user->profile->username }}</a>
                                </span>
                                <span class="description">{{ $post->created_at->format('H:i d/m/Y') }}</span>
                            </div>
                            <!-- /.user-block -->
                            <div class="col mb-3">
                                <div class="row-sm-6">
                                    <img class="img-fluid" src="{{ asset('gambar/' . $post->gambar) }}" alt="Photo">
                                </div>
                                <div class="row">
                                    <p>
                                        {{ $post->konten }}
                                    </p>
                                </div>
                            </div>
                            <p>
                                <a href="#" class="link-black text-sm btn-link disabled"><i
                                        class="far fa-thumbs-up mr-1"></i>
                                    {{ $post->postLike->count() }} Like</a>
                                <a href="#" class="link-black text-sm btn-link disabled">
                                    <i class="far fa-comments mr-1"></i> Comments
                                    ({{ $post->komentar->count() }})
                                </a>
                                @auth
                                <div class="d-flex">
                                    @if (!$post->likedBy(auth()->user()))
                                    <form action="{{ route('postlike.store',['postlike'=>$post->id]) }}" method="POST">
                                        @csrf
                                        <button type="submit" class="btn btn-primary btn-sm  mr-2"><i
                                                class="far fa-heart ml-0 mr-1"></i> Like</button>
                                    </form>
                                    @else
                                    <form action="{{ route('postlike.destroy',['postlike'=>$post->id]) }}"
                                        method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-secondary btn-sm  mr-2"><i
                                                class="fas fa-heart-broken ml-0 mr-1"></i> Unlike</button>
                                    </form>
                                    @endif
                                    @if ($post->user_id === Auth::user()->id)
                                    <a href="{{ route('post.edit',['post' => $post->id]) }}"
                                        class="btn btn-info btn-sm  mr-2"><i class="far fa-edit ml-1 mr-1"></i>
                                        Edit</a>
                                    <form action="{{ route('post.destroy', ["post" => $post->id]) }}" method="POST">
                                        @csrf
                                        @method("DELETE")
                                        <button type="submit" class="btn btn-danger btn-sm  ml-0"><i
                                                class="far fa-trash-alt ml-1 mr-1"></i> Delete</button>
                                    </form>
                                    @endif
                                </div>
                                @endauth
                                {{-- <span class="float-right">
                                    <a href="{{ route('post.show',['post' => $post->id]) }}" class="link-black
                                text-sm">
                                <i class="far fa-comments mr-1"></i> Comments (5)
                                </a>
                                </span> --}}
                            </p>
                            <!-- /.row -->
                            @auth
                            <div>
                                <form method="POST" action="{{ route('komentar.store') }}">
                                    @csrf
                                    <div class="input-group mb-3">
                                        <textarea name="komen" id="komen"
                                            class="form-control @error('komen') is-invalid @enderror"
                                            placeholder="Enter Comment">{{ old('komen','') }}</textarea>
                                        @error('komen')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <input type="hidden" name="post_id" value="{{ $post->id }}">
                                    <button type="submit" class="btn btn-primary btn-block">Add Comment</button>
                                </form>
                            </div>
                            <hr>
                        </div>
                        @endauth
                        <!-- /.post -->

                    </div><!-- /.card-body -->
                    <div class="card-footer card-comments">
                        @forelse ($post->komentar as $komen)
                        <div class="card-comment">
                            <!-- User image -->
                            <img class="img-circle img-sm" src="{{ asset('adminlte/dist/img/guest.png') }}"
                                alt="User Image">

                            <div class="comment-text">
                                <span class="username">
                                    {{ $komen->user->profile->username }}
                                    <span
                                        class="text-muted float-right">{{ $komen->created_at->format('H:i d/m/Y') }}</span>
                                </span><!-- /.username -->
                                <div class="col">
                                    <div class="row">
                                        {{ $komen->komen }}
                                    </div>
                                    <div class="row">
                                        <a href="#" class="link-black text-sm btn-link disabled"><i
                                                class="far fa-thumbs-up mr-1"></i>
                                            {{ $komen->komentarLike->count() }} Like</a>
                                    </div>
                                    <div class="row">
                                        <p>
                                            @auth
                                            <div class="d-flex">
                                                @if (!$komen->likedBy(auth()->user()))
                                                <form
                                                    action="{{ route('komentarlike.store',['komentarlike'=>$komen->id]) }}"
                                                    method="POST">
                                                    @csrf
                                                    <button type="submit" class="btn btn-primary btn-sm  mr-2"><i
                                                            class="far fa-heart ml-0 mr-1"></i> Like</button>
                                                </form>
                                                @else
                                                <form
                                                    action="{{ route('komentarlike.destroy',['komentarlike'=>$komen->id]) }}"
                                                    method="POST">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-secondary btn-sm  mr-2"><i
                                                            class="fas fa-heart-broken ml-0 mr-1"></i> Unlike</button>
                                                </form>
                                                @endif
                                                @if ($komen->user_id === Auth::user()->id)
                                                <form
                                                    action="{{ route('komentar.destroy', ["komentar" => $komen->id]) }}"
                                                    method="POST">
                                                    @csrf
                                                    @method("DELETE")
                                                    <button type="submit" class="btn btn-danger btn-sm  ml-0"><i
                                                            class="far fa-trash-alt ml-1 mr-1"></i> Delete</button>
                                                </form>
                                                @endif
                                            </div>
                                            @endauth
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <!-- /.comment-text -->
                        </div>
                        @empty
                        <p>No Comment</p>
                        @endforelse
                    </div>
                    <!-- /.card-footer -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection